/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.tiketpesawat;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import tiketpesawat.*;

public class PemesananUI extends javax.swing.JFrame {
    public Pembeli objPembeli;
    public Pesawat objPesawat;
    public Rute objRute;
    public Tiket objTiket;
    /**
     * Creates new form IdentitasUI
     */
    public PemesananUI() {
        initComponents();
        objPembeli = new Pembeli();
        objPesawat = new Pesawat();
        objRute = new Rute();
        objTiket = new Tiket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biaya2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_pembeliFrame = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama_pembeliFrame = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        usiaFrame = new javax.swing.JTextField();
        kode_pesawatFrame = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama_pesawatFrame = new javax.swing.JTextField();
        kode_ruteFrame = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rute_pesawatFrame = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kelas_pesawatFrame = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jumlah_tiketFrame = new javax.swing.JTextField();
        total_biayaFrame = new javax.swing.JTextField();
        biayaFrame = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        uang_bayarFrame = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        kembalianFrame = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        uang_kembalianFrame = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pesanFrame = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        biaya2.setText("Kembalian");
        biaya2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biaya2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pemesanan Tiket Pesawat");

        jLabel3.setText("No.ID(KTP,SIM,Paspor)");

        id_pembeliFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pembeliFrameActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        nama_pembeliFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pembeliFrameActionPerformed(evt);
            }
        });

        jLabel7.setText("Usia");

        kode_pesawatFrame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "MPT", "GRD", "BTV" }));
        kode_pesawatFrame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kode_pesawatFrameItemStateChanged(evt);
            }
        });
        kode_pesawatFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_pesawatFrameActionPerformed(evt);
            }
        });

        jLabel2.setText("Kode Pesawat");

        jLabel8.setText("Nama Pesawat");

        kode_ruteFrame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "TKG-CGK", "CGK-TKG", "TKG-DPS" }));
        kode_ruteFrame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kode_ruteFrameItemStateChanged(evt);
            }
        });
        kode_ruteFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_ruteFrameActionPerformed(evt);
            }
        });

        jLabel5.setText("Kode Rute");

        jLabel6.setText("Rute");

        kelas_pesawatFrame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Kelas 1", "Kelas 2", "Kelas 3" }));
        kelas_pesawatFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelas_pesawatFrameActionPerformed(evt);
            }
        });

        jLabel9.setText("Kelas Pesawat");

        jLabel10.setText("Jumlah Tiket");

        jumlah_tiketFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_tiketFrameActionPerformed(evt);
            }
        });

        biayaFrame.setText("Biaya");
        biayaFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaFrameActionPerformed(evt);
            }
        });

        jLabel11.setText("Total Biaya");

        jLabel12.setText("Rp.");

        jLabel13.setText("Uang Pembayaran");

        uang_bayarFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uang_bayarFrameActionPerformed(evt);
            }
        });

        jLabel14.setText("Rp.");

        kembalianFrame.setText("Kembalian");
        kembalianFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianFrameActionPerformed(evt);
            }
        });

        jLabel15.setText("Uang Kembalian");

        jLabel16.setText("Rp.");

        pesanFrame.setText("Pesan");
        pesanFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanFrameActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pesanFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama_pesawatFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(rute_pesawatFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(nama_pembeliFrame)
                            .addComponent(id_pembeliFrame)
                            .addComponent(total_biayaFrame)
                            .addComponent(uang_bayarFrame)
                            .addComponent(uang_kembalianFrame)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(biayaFrame)
                                    .addComponent(kode_ruteFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kode_pesawatFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usiaFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kelas_pesawatFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlah_tiketFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kembalianFrame)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_pembeliFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama_pembeliFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usiaFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_pesawatFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama_pesawatFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_ruteFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rute_pesawatFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelas_pesawatFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jumlah_tiketFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_biayaFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biayaFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(uang_bayarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kembalianFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uang_kembalianFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanFrame)
                    .addComponent(cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelas_pesawatFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelas_pesawatFrameActionPerformed
        if(kode_pesawatFrame.getSelectedItem().equals("MPT")){
            if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 1")){
                objTiket.harga_tiket = 1500000;
            }else if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 2")){
                objTiket.harga_tiket = 900000;
            }else if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 3")){
                objTiket.harga_tiket = 500000;
            }
        }else if(kode_pesawatFrame.getSelectedItem().equals("GRD")){
            if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 1")){
                objTiket.harga_tiket = 1200000;
            }else if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 2")){
                objTiket.harga_tiket = 800000;
            }else if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 3")){
                objTiket.harga_tiket = 400000;
            }
        }else if(kode_pesawatFrame.getSelectedItem().equals("BTV")){
            if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 1")){
                objTiket.harga_tiket = 1000000;
            }else if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 2")){
                objTiket.harga_tiket = 700000;
            }else if(kelas_pesawatFrame.getSelectedItem().equals("Kelas 3")){
                objTiket.harga_tiket = 300000;
            }
        }
    }//GEN-LAST:event_kelas_pesawatFrameActionPerformed

    private void kode_ruteFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_ruteFrameActionPerformed
        if(kode_ruteFrame.getSelectedItem().equals("TKG-CGK")){
            rute_pesawatFrame.setText("Lampung-Jakarta");
        }else if(kode_ruteFrame.getSelectedItem().equals("CGK-TKG")){
            rute_pesawatFrame.setText("Jakarta-Lampung");
        }else if(kode_ruteFrame.getSelectedItem().equals("TKG-DPS")){
            rute_pesawatFrame.setText("Lampung-Bali");
        }
        objRute.kode_rute = (String) kode_ruteFrame.getSelectedItem();
        objRute.rute_penerbangan = rute_pesawatFrame.getText();
    }//GEN-LAST:event_kode_ruteFrameActionPerformed

    private void kode_ruteFrameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kode_ruteFrameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_ruteFrameItemStateChanged

    private void kode_pesawatFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_pesawatFrameActionPerformed
        if(kode_pesawatFrame.getSelectedItem().equals("MPT")){
            nama_pesawatFrame.setText("Merpati");
        }else if(kode_pesawatFrame.getSelectedItem().equals("GRD")){
            nama_pesawatFrame.setText("Garuda");
        }else if(kode_pesawatFrame.getSelectedItem().equals("BTV")){
            nama_pesawatFrame.setText("Batavia");
        }
        objPesawat.kode_pesawat = (String) kode_pesawatFrame.getSelectedItem();
        objPesawat.nama_pesawat = nama_pesawatFrame.getText();
    }//GEN-LAST:event_kode_pesawatFrameActionPerformed

    private void kode_pesawatFrameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kode_pesawatFrameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_pesawatFrameItemStateChanged

    private void nama_pembeliFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pembeliFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pembeliFrameActionPerformed

    private void biayaFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaFrameActionPerformed
        objTiket.jumlah_tiket = Integer.parseInt(jumlah_tiketFrame.getText());
        int harga = objTiket.harga_tiket;
        int jumlah = objTiket.jumlah_tiket;
        int hasil = harga*jumlah;
        total_biayaFrame.setText(Integer.toString(hasil));
    }//GEN-LAST:event_biayaFrameActionPerformed

    private void kembalianFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianFrameActionPerformed
        objTiket.total_biaya = Integer.parseInt(total_biayaFrame.getText());
        objTiket.uang_bayar = Integer.parseInt(uang_bayarFrame.getText());
        int uang = objTiket.uang_bayar;
        int biaya = objTiket.total_biaya;
        int kembali = uang-biaya;
        uang_kembalianFrame.setText(Integer.toString(kembali));
    }//GEN-LAST:event_kembalianFrameActionPerformed

    private void biaya2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biaya2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biaya2ActionPerformed

    private void pesanFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanFrameActionPerformed
        objPembeli.id_pembeli = id_pembeliFrame.getText();
        objPembeli.nama_pembeli = nama_pembeliFrame.getText();
        objPembeli.usia = Integer.parseInt(usiaFrame.getText());
        id_pembeliFrame.setText("");
        nama_pembeliFrame.setText("");
        usiaFrame.setText("");
        nama_pesawatFrame.setText("");
        kode_ruteFrame.setSelectedIndex(0);
        rute_pesawatFrame.setText("");
        jumlah_tiketFrame.setText("");
        total_biayaFrame.setText("");
        uang_bayarFrame.setText("");
        uang_kembalianFrame.setText("");
        kelas_pesawatFrame.setSelectedIndex(0);
        kode_pesawatFrame.setSelectedIndex(0);
        JOptionPane.showMessageDialog(null,"Terima Kasih. Pesanan Anda akan kami proses.");
        System.exit(0);
    }//GEN-LAST:event_pesanFrameActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void id_pembeliFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pembeliFrameActionPerformed
        
    }//GEN-LAST:event_id_pembeliFrameActionPerformed

    private void jumlah_tiketFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_tiketFrameActionPerformed
        objTiket.jumlah_tiket = Integer.parseInt(jumlah_tiketFrame.getText());
    }//GEN-LAST:event_jumlah_tiketFrameActionPerformed

    private void uang_bayarFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uang_bayarFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uang_bayarFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biaya2;
    private javax.swing.JButton biayaFrame;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField id_pembeliFrame;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlah_tiketFrame;
    private javax.swing.JComboBox<String> kelas_pesawatFrame;
    private javax.swing.JButton kembalianFrame;
    private javax.swing.JComboBox<String> kode_pesawatFrame;
    private javax.swing.JComboBox<String> kode_ruteFrame;
    private javax.swing.JTextField nama_pembeliFrame;
    private javax.swing.JTextField nama_pesawatFrame;
    private javax.swing.JButton pesanFrame;
    private javax.swing.JTextField rute_pesawatFrame;
    private javax.swing.JTextField total_biayaFrame;
    private javax.swing.JTextField uang_bayarFrame;
    private javax.swing.JTextField uang_kembalianFrame;
    private javax.swing.JTextField usiaFrame;
    // End of variables declaration//GEN-END:variables
}
